dist: xenial
sudo: required

language: c
compiler: gcc
os: linux

env:
  global:
    - NUM_THREADS=4

before_install:
  - pip install --user cpp-coveralls
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y autoconf
  - sudo apt-get install -y automake
  - sudo apt-get install -y libtool
  - sudo apt-get install -y m4 
  - sudo apt-get install -y lcov
  - sudo apt-get install -y perl
  - sudo apt-get install -y pkg-config
  - sudo apt-get install -y libdrm-dev
  - sudo apt-get install -y autoconf
  - sudo apt-get install -y libegl1-mesa-dev
  - sudo apt-get install -y libgl1-mesa-dev
  - sudo apt-get install -y libwayland-dev
  - sudo apt-get install -y libx11-dev
  - sudo apt-get install -y libxext-dev
  - sudo apt-get install -y libxfixes-dev
  
script:
        - ./autogen.sh
        - ./configure --prefix=/usr
        - make -j4 ; sudo make install
        - make check

after_success:
        - coveralls --exclude lib --exclude tests --gcov-options '\-lp'

notifications:
# Emails are sent to the committer's git-configured email address by default,
# but only if they have access to the repository.  To enable Travis on your
# public fork of Caffe, just go to travis-ci.org and flip the switch on for
# your Caffe fork.  To configure your git email address, use:
#     git config --global user.email me@example.com
  email:
    on_success: always
    on_failure: always

# Slack notifications
#
  slack: intel-media:p0wZO3fWJ1ouSsF0RNKbOl5G

# IRC notifications disabled by default.
# Uncomment next 5 lines to send notifications to chat.freenode.net#caffe
#   irc:
#     channels:
#       - "chat.freenode.net#intel-media"
#     template:
#       - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
